<?php
   include_once("common/authorize.php");
   include_once('functions/conn.php');
   //Generating Bill number
   $billProcced = 0;
   if(isset($_SESSION["sessionBillNo"]))
   {        
      $billid = $_SESSION["sessionBillNo"]; 
      $sessionResult = $mysqli->query("SELECT * from bill where billid = '$billid'");
      $sessionResult2 = $mysqli->query("SELECT * from bill where billid = '$billid'");
      $billProcced = 1;
     
      if(isset($_SESSION["newCusid"])){
         $newCusid = $_SESSION["newCusid"];
      }
      $initialCusid = $_SESSION["initialCusid"];
   }
   else
   {
      $billSql = $mysqli->query("SELECT billid, billno from bill ORDER BY billno DESC");
      $count = mysqli_num_rows($billSql); 
      if($count == 0){
         $billNo = "0000001";
         $billProcced = 0;
      }
      else{
      $billRow = mysqli_fetch_assoc($billSql);
      $billid = $billRow['billid']+1;
      $billProcced = 1;
      }
   }
   
   //if bill is not generated by above process
   if($billProcced == 1 ){
      
      $count = strlen((string)$billid);
      //$count = count number of integer in database
      $zero = 7 - $count;
      $x = '';
      for($i = 0; $i < $zero; $i++ ){
         $x .= '0';
      }
      $billNo = $x.($billid);
   } 
   
   //Changing product detail on index change
   //if once customer is selected and not enter done button
   if(isset($_SESSION["initialCusid"]) && $_SESSION["initialCusid"] != "none"){
      $cusId = $_SESSION["initialCusid"];
      $customerSql = "SELECT * FROM customer WHERE id = '$cusId'";   
   }
   else{
      $customerSql = "SELECT * FROM customer order by name";   
   }
   $csResult = $mysqli-> query($customerSql);
   function fill_brand($mysqli){
      $output = '';
   
      $sql = "select * from stock order by name";
      $result  = mysqli_query($mysqli, $sql);
      while ($row = mysqli_fetch_array($result)){
         $output .= '<option value = "'.$row['id'].'">'.$row['name'].' </option>';
      }
      return $output;
   }
   
   function fill_product($mysqli){
         $output = '';
         $sql = "SELECT * FROM stock order by name ASC LIMIT 1 ";
         $result  = mysqli_query($mysqli, $sql);
   
         while($row = mysqli_fetch_array($result)){
            if($row['type'] == "sack"){
               $unit = 'KG';
            }
            else{
               $unit = 'Piece';
            }
   
            $output .=  '<div class="input" >
            <label > Product Comes in <label id = "pType">'.$row["type"].'</label>,<i style = "color:blue"> 1 </i>'.$row["type"].' contains 
            </label>
            <label ><i style = "color:blue"> <label id = "amtType"> '.$row["amountPtype"]. ' '. $unit.' <label> </i> of '. $row["name"].'
            </label>
            </div>
            <div class="input" >
            <label > Wholesell Price:<i style = "color:blue"> <label id = "wp">'.$row["wholesell"].'</label></i> 
            </label>
            </div>
            <div class="input" >
            <label > Sell Price: <i style = "color:blue"> <label id = "sp">'.$row["sell"].'</label></i>
            </label>
            </div>
            <div class="input">
            <label > Retail Price : <i style = "color:blue"> <label id = "rp">'.$row["retail"].'</label></i>
           </div>
            ';
         }
         return $output;
      }
      
   ?>
<!DOCTYPE html>
<html>
   <head>
      <title>Billing</title>
      <?php include_once("common/link.php"); ?>
      <link rel="stylesheet" type="text/css" href="css/body.css">
      <script src="js/jQuery.js"></script>
      <script src="bootstrap/js/bootstrap.min.js"></script>
   </head>
   <body onload=printdate();>
      <!-- <div class="row"> -->
      <?php
         include_once("common/header.php");
         ?>
      <div class="col-md-10">
         <?php if (isset($_GET['msg'])){
            echo $_GET['msg'];
            }    
            ?> 
         <h3>Billing Management.</h3>
         <i>If you want to manage customer, go to <a href="customer.php"> Customer page</a></i>
         <!-- SCREENING ADD FORM  _________________ START -->
         <div class="billForm" id="">
            <div class="billWrapper grid">
               <h1> Sirjita stores</h1>
               <div class = "date">
                  <label  style = "margin-right:20px;">Bill no: <?php echo $billNo; ?> </label>
                  <label>Time:</label>  
                  <input id = 'inputTime'  type = 'text' placeholder = '12:00 AM' required = "required" value = ''>
                  <label>Date:</label>
                  <input id = 'inputDate'  type = 'text' placeholder = '2001-01-01' required = "required" value = ''>
               </div>
               <form id="jsform" method="POST" action="functions/obj.php">
               <input id = 'inputTime2' name = "inputTime" type = 'text' placeholder = '12:00 AM' required = "required" style = "display:none;">
               <input id = 'inputDate2' name = "inputDate" type = 'text' placeholder = '2001-01-01' required = "required" style = "display:none;">
               <input name = 'bill_no' type = 'number' required = "required" value = '<?php echo $billNo; ?>' style = "display:none;">
                  <div class="radioWrapper">
                     <div class="input1">
                        <label>Type of customer: </label>
                        <input type="radio" name="type" checked = "checked" required = "required" value="existing" onclick="billradio()">
                        <label> Existing</label>
                        <input type="radio" name="type"  value="new"  onclick="billradio()" >
                        <label>Add New</label>
                     </div>
                  </div>
                  <div class="inputWrapper " id= "oldwrap">
                     <div class="inputHr">
                        <label> Select Customer:</label>
                        <select name="customerId" id ="customerId">
                        <?php
                           if($csResult->num_rows >0){
                               while($row = mysqli_fetch_assoc($csResult)){
                               echo " <option value='". $row['id']."' >".$row['name']." </option> ";
                               }
                           }      
                           ?>
                        </select>                 
                     </div>
                  </div>
                  <div class="inputWrapper noVisible" id= "newwrap">
                     <div class="inputHr">
                        <label > Name: </label>
                        <input Type="text" id= "inputName" name="cus_name"  placeholder="eg. John Doe">
                     </div>
                     <div class="inputHr">
                        <label > Type: </label>
                        <select name="cus_type">
                           <option value = "old">Old</option>
                           <option value = "new">New</option>
                        </select>
                     </div>
                     <div class="inputHr">
                        <label > Address: </label>
                        <input Type="text" id= "inputAdr"  name="address"   placeholder="eg. Denver-24 Street, USA">
                     </div>
                     <div class="inputHr">
                        <label > Phone: </label>
                        <input Type="number" id= "inputNum" step="1" name="phone"   placeholder="eg. 986923142 ">
                     </div>
                  </div>
                  <div class="inputWrapper" id= "">
                     <div class="inputHr">
                        <label > Product: </label>
                        <select name="product" id = "brand" onchange = "billingTotal()">
                        <?php echo fill_brand($mysqli); ?>
                        </select>
                     </div>
                     <div class="inputHr">
                        <label > Quantity (sack or catroon) : </label>
                        <input Type="number" id = "quantity" step="1" name="quantity" required = "required" onkeyup = "billingTotal()" placeholder="eg. 5 Catroon">
                     </div>
                     <div class="inputHr">
                        <label > Amount (kg or Piece) : </label>
                        <input Type="number" id = "amount" step="0.5" name="amount"  required = "required" onkeyup = "billingTotal()" placeholder="eg. 25 piece ">
                     </div>
                  </div>
                  <div class="blngPrs-Wrapper" id= "">
                     <div class="input">
                        <label > Apply: </label>
                        <select name="rate" id= "rateType" onchange = "billingTotal()">
                           <option value = "wp">Wholesell Rate</option>
                           <option value = "sp">Sell Rate</option>
                           <option value = "rp">Retail Rate</option>
                        </select>
                     </div>
                     <div id= "show_product">
                        <?php echo fill_product($mysqli); ?>
                     </div>
                     <div class="input"><i style = "color:blue">  <label id = "total"> Total : 0 </label></i>
                     </div>
                     <div class="input"> <label > Manual Total: </label>
                     <input Type="number" id= "vat" step="0.1" name="total" required = "required" style = "color:blue">
                     </div>
                     <div class="input">
                        <label id="error" style="color:red; text-transform: none;">  </label>
                     </div>
                  </div>
                  <div class="button d-flex justify-content-end">
                     <button type="submit" id="screeningBtn" name = "billingBtn" onclick= "return confirm('Are you sure wanna Add?');" style = "margin-top:-40px">  Add data</button>
                  </div>
               </form>
            </div>
         </div>
         <!-- //displaying Bill  -->               
         <?php 
         if(isset($_SESSION["sessionBillshow"]) && $_SESSION["sessionBillshow"] == "visible"){ 
            if(isset($_SESSION["sessionBillNo"])){ 
            $row2 = mysqli_fetch_assoc($sessionResult);
            $cusres = $mysqli->query("SELECT * FROM customer WHERE id = '$initialCusid'");
            $cusrow = mysqli_fetch_assoc($cusres);
            ?>

         <section class = "bill" id = "billview">
            <div class = "u_bill">
               <h2>Sirjita Stores</h2>
               <h3>Kalika - 28, Kaski</h3>
               <h4>customer Bill</h4>
               <div class = "date">
                  <label>Bill no: <?php echo $billNo; ?> </label>
                  <label>Time: <?php echo $row2['time']; ?></label>  
                  <label>Date: <?php echo $row2['date']; ?></label>
               </div>
               <div class = "name">
                  <label >Name: <?php echo $cusrow['name']; ?></label>
                  <label>Address: <?php echo $cusrow['address']; ?> </label>  
                  <label>Phone: <?php echo $cusrow['phone']; ?> </label>  
               </div>
            </div>
            <div class = "l_bill">
               <div >
                  <table class="table table-bordered" style="background-color:rgb(255, 245, 238)" >
                     <thead class="thead-light">
                        <tr>
                           <th scope="col">#</th>
                           <th scope="col">Product</th>
                           <th scope="col">Product in Quantity</th>
                           <th scope="col">Product in Amount</th>
                           <th scope="col">Total Product</th>
                           <th scope="col">Rate Type</th>
                           <th scope="col">Total</th>
                        </tr>
                     </thead>
                     <tbody>
                        <?php
                           if($sessionResult->num_rows >0){
                              $i = 1;
                              $grandTotal = 0;
                              while($row1 = mysqli_fetch_assoc($sessionResult2) ){
                           ?>   
                        <tr>
                           <th scope='row'> <?php echo $i ?> </th>
                           <td>  <?php echo $row1['p_name'] ?> </td>
                           <td>  <?php echo $row1['qty'] . ' '. $row1['pType']; ?> </td>
                           <td>  <?php echo $row1['amount'];
                              if($row1['pType'] == "Sack"){
                                 echo ' kg ';
                              }
                              else{
                              echo ' Piece ';
                              }  ?>
                           </td>
                           <td>  <?php echo $row1['total_qty'];
                              if($row1['pType'] == "Sack"){
                                 echo ' kg ';
                              }
                              else{
                              echo ' Piece ';
                              }  ?>
                           </td>
                           <td>  <?php echo $row1['rate_type'] ?> </td>
                           <td> RS  <?php echo $row1['total'] ?> </td>
                           <td> 
                           <form method="POST" action="functions/obj.php" style="display:block; margin:0px; padding:0px"> 
                           <input type = "text" name = "qty" value = "<?php echo $row1['qty']; ?>" style="display:none" >
                           <input type = "text" name = "amount" value = "<?php echo $row1['amount']; ?>" style="display:none" >
                           <input type = "text" name = "Pid" value = "<?php echo $row1['Pid']; ?>" style="display:none" >
                           <input type = "text" name = "id" value = "<?php echo $row1['id']; ?>" style="display:none" >
                           <button style="border:none; background:none" type="submit" name="deleteP" onclick="return confirm('Are you sure you want to delete this Item?');" title="Click here to delete this data"> 
                           <i class="fas fa-trash-alt" style="color:red"></i>
                           </button>
                           </form>                           
                        </td>
                        </tr>
                        <?php $i++; $grandTotal+= $row1['total'];
                        } } ?> 
                     </tbody>
                  </table>
               </div>
            </div>
            <div class = "l_bill">
               <form method = "POST" action="functions/obj.php">
                  <input  type = 'text'  name = "inputTime" placeholder = '12:00 AM' required = "required" value = '<?php echo $row2['time']; ?>' style = "display:none;">
                  <input  type = 'text' name = "inputDate" placeholder = '2001-01-01' required = "required" value = '<?php echo $row2['date']; ?>' style = "display:none;">
                  <div class="input">
                     <label style = "font-weight:bold;" > Grand Total: <label style = "color: rebeccapurple;"><?php echo $grandTotal; ?> </label></label>
                  </div>
                  <div class="input"> <label > Total Including Vat : </label>
                     <input Type="number" id= "vat" step="0.5" name="vat" required = "required" >
                     <input Type="text" id= "vat"  name="grand" value = "<?php echo $grandTotal; ?> " style = "display:none" >
                     <input Type="text" id= "vat"  name="bill" value = "<?php echo $billNo; ?> " style = "display:none" >
                  </div>
                  <div class="input"> <label > Amount Paid: </label>
                     <input Type="number" id= "vat" step="0.1" name="paid" required = "required" >
                  </div>
                  <div class="input"> <label > In Word : </label>
                     <input Type="text" id= "vat" step="0" name="word" style = "width:70%;" >
                  </div>
                  <div class="input">
                     <input type="radio" name="amt_type"  value="cash" required = "required">
                     <label> Cash</label>
                     <input type="radio" name="amt_type"  value="cheque"  >
                     <label>Cheque</label>
                     <input type="radio" name="amt_type"  value="credit"  >
                     <label>Credit</label>
                  </div>
                  <div class="button d-flex justify-content-end">
                  <button type="submit" name = "sessionBill" onclick= "return confirm('Are you sure?');"  style = "margin-right:40px">  Done</button>
                  </div>
               </form>
            </div>
         </section>               
         <?php } }?>
      </div>
      </div>
      <script src="js/admin.js"></script>
      <script>
         var icon = document.getElementById('menu');
         var Menu = document.getElementById('dropdownMenu');
         icon.onclick = function() {
             if (Menu.className === "col-md-2") {
                 Menu.classList.add("menuActive");
             } else {
                 Menu.className = "col-md-2";
             }
         }
      </script>
      <script>
         $(document).ready(function(){
            $('#brand').change(function(){
               var brand_id = $(this).val();
         
               $.ajax({
                  url:"load_data.php",
                  method:"POST",
                  data:{brand_id:brand_id},
                  success: function(data){
                     $('#show_product').html(data);
                  }
               });
            });
         });
      </script>
   </body>
</html>

